## project name is set in the .env file

version: '2'


services:

  figwheel:
    image: koddo/lein
    volumes:
      - ./client-web:/home/theuser/theproject
      - ./client-web/lein-deps:/home/theuser/.m2/      # cache dependencies of lein figwheel to avoid downloading them on every run, this is gitignored
    working_dir: /home/theuser/theproject
    command: lein figwheel
    ports:
      - "3449:3449"

  gulp:
    image: koddo/gulp
    volumes:
      - ./client-web/less:/home/node/prj/src
      - ./client-web/resources/public/css:/home/node/prj/dest

  flask-static:
    image: koddo/flask-static
    volumes:
      - ./client-web/resources/public:/home/theuser/static
    ports:
      - "3448:3448"

  browser-console-logger:
    image: koddo/browser-console-logger
    ports:
      - "9907:9907"

## -----------------

  backend:
    image: koddo/erlang
    volumes:
      - ./backend:/home/theuser/theproject
      - ./client-web/resources/public:/home/theuser/theproject/priv
      - ./database/certs_dev:/home/theuser/certs_dev
      - ../superlearn.secrets:/home/theuser/secrets
    working_dir: /home/theuser/theproject
    entrypoint:  /home/theuser/theproject/docker-entrypoint-backend.sh
    ports:
      - "8080:8080"

  nginx:
    image: nginx
    ports:
        - "8443:8443"
    volumes:
        - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/server.crt:/etc/nginx/server.crt:ro
        - ./nginx/server.key:/etc/nginx/server.key:ro
        - ./client-web/resources/public:/var/www:ro

## -----------------

  database:
    image: koddo/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data   # this is the default value
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - superlearn_pgdata:/var/lib/postgresql/data
      # we can't share files here directly, because at the moment of writing docker doesn't allow to map uids in volumes, so we simply copy these files using a copy.sh script


## -----------------


volumes:
  superlearn_pgdata:
    external: true






