PROJECT = hello_world
PROJECT_DESCRIPTION = Cowboy Hello World example
PROJECT_VERSION = 1

RELX_CONFIG = relx-dev.config

DTL_PATH = erlydtl/

DEPS = cowboy epgsql erlydtl jsx erlware_commons
dep_cowboy_commit = master

include erlang.mk

## later:
# lager
# base64url
# https://github.com/manifest/pal-google-oauth2
